/**
 * Shared i18n resources & language metadata for the ENGRAM web and mobile apps.
 *
 * - `src/en/*.json` are the authoring source of truth — one JSON file per
 *   namespace, hand-edited alongside feature work.
 * - `src/generated/<lang>.json` are full-tree translations generated by
 *   `pnpm --filter @workspace/scripts run generate:locales` (AI-assisted).
 *   Do not hand-edit; re-run the generator after changing the English files.
 */
import common from "./en/common.json";
import nav from "./en/nav.json";
import settings from "./en/settings.json";
import home from "./en/home.json";
import analytics from "./en/analytics.json";
import beliefs from "./en/beliefs.json";
import chat from "./en/chat.json";
import commons from "./en/commons.json";
import download from "./en/download.json";
import environment from "./en/environment.json";
import evolution from "./en/evolution.json";
import hieroCode from "./en/hieroCode.json";
import hub from "./en/hub.json";
import inquiry from "./en/inquiry.json";
import journal from "./en/journal.json";
import media from "./en/media.json";
import memory from "./en/memory.json";
import notFound from "./en/notFound.json";
import personality from "./en/personality.json";
import personas from "./en/personas.json";
import simulations from "./en/simulations.json";
import studio from "./en/studio.json";
import terminal from "./en/terminal.json";
import worldModel from "./en/worldModel.json";
import mobile from "./en/mobile.json";
import createEngram from "./en/createEngram.json";

import es from "./generated/es.json";
import fr from "./generated/fr.json";
import de from "./generated/de.json";
import pt from "./generated/pt.json";
import it from "./generated/it.json";
import ru from "./generated/ru.json";
import ja from "./generated/ja.json";
import ko from "./generated/ko.json";
import zh from "./generated/zh.json";
import ar from "./generated/ar.json";
import hi from "./generated/hi.json";

export const enResources = {
  common,
  nav,
  settings,
  home,
  analytics,
  beliefs,
  chat,
  commons,
  download,
  environment,
  evolution,
  hieroCode,
  hub,
  inquiry,
  journal,
  media,
  memory,
  notFound,
  personality,
  personas,
  simulations,
  studio,
  terminal,
  worldModel,
  mobile,
  createEngram,
} as const;

export type I18nNamespace = keyof typeof enResources;

export const NAMESPACES = Object.keys(enResources) as I18nNamespace[];

type ResourceTree = Record<string, unknown>;

/** i18next-shaped resources: { lang: { namespace: {...} } } */
export const resources: Record<string, Record<string, ResourceTree>> = {
  en: enResources as unknown as Record<string, ResourceTree>,
  es: es as Record<string, ResourceTree>,
  fr: fr as Record<string, ResourceTree>,
  de: de as Record<string, ResourceTree>,
  pt: pt as Record<string, ResourceTree>,
  it: it as Record<string, ResourceTree>,
  ru: ru as Record<string, ResourceTree>,
  ja: ja as Record<string, ResourceTree>,
  ko: ko as Record<string, ResourceTree>,
  zh: zh as Record<string, ResourceTree>,
  ar: ar as Record<string, ResourceTree>,
  hi: hi as Record<string, ResourceTree>,
};

export interface LanguageInfo {
  /** BCP-47 code, also the i18next language key. */
  code: string;
  /** English name (used in prompts sent to the model). */
  englishName: string;
  /** Autonym shown in language pickers. */
  nativeName: string;
  /** Right-to-left script. */
  rtl: boolean;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: "en", englishName: "English", nativeName: "English", rtl: false },
  { code: "es", englishName: "Spanish", nativeName: "Español", rtl: false },
  { code: "fr", englishName: "French", nativeName: "Français", rtl: false },
  { code: "de", englishName: "German", nativeName: "Deutsch", rtl: false },
  { code: "pt", englishName: "Portuguese", nativeName: "Português", rtl: false },
  { code: "it", englishName: "Italian", nativeName: "Italiano", rtl: false },
  { code: "ru", englishName: "Russian", nativeName: "Русский", rtl: false },
  { code: "ja", englishName: "Japanese", nativeName: "日本語", rtl: false },
  { code: "ko", englishName: "Korean", nativeName: "한국어", rtl: false },
  { code: "zh", englishName: "Chinese (Simplified)", nativeName: "简体中文", rtl: false },
  { code: "ar", englishName: "Arabic", nativeName: "العربية", rtl: true },
  { code: "hi", englishName: "Hindi", nativeName: "हिन्दी", rtl: false },
];

export const SUPPORTED_LANGUAGE_CODES = LANGUAGES.map((l) => l.code);

export const DEFAULT_LANGUAGE = "en";

export function languageInfo(code: string | null | undefined): LanguageInfo | undefined {
  if (!code) return undefined;
  const norm = code.toLowerCase().split("-")[0];
  return LANGUAGES.find((l) => l.code === norm);
}

/**
 * Build the model-facing instruction for an explicit reply-language preference.
 * Returns empty string for unknown/absent codes (automatic: match the user).
 */
export function responseLanguageInstruction(code: string | null | undefined): string {
  const info = languageInfo(code);
  if (!info) return "";
  return `The operator has set their preferred language to ${info.englishName} (${info.nativeName}). Respond in ${info.englishName} regardless of the language they write in, unless they explicitly ask you to switch. Keep your characteristic formatting, names, and signature vocabulary/catchphrases intact.`;
}
