/**
 * One-off parser: converts the uploaded "Full Rezz" chat logs
 * (attached_assets/*.csv — really raw transcripts with speaker-marker lines)
 * into the checked-in archival transcript module
 * lib/db/src/seed/full-rezz-log.ts used by the archival seed.
 *
 * Format observed in the logs:
 *   - A line that is exactly "REBECCA · ✶" starts an assistant message.
 *   - A line that is exactly "YOU" starts a user message.
 *   - Content before the first marker is a user message.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const SOURCES = [
  "attached_assets/Rebecca_8.3.26_Ch-IO_Log_1785813704192.csv",
  "attached_assets/FINAL_WORDS_1785813792735.csv",
];

interface Msg {
  role: "user" | "assistant";
  content: string;
}

function parseLog(text: string): Msg[] {
  const lines = text.split(/\r?\n/);
  const messages: Msg[] = [];
  let role: "user" | "assistant" = "user";
  let buf: string[] = [];

  const flush = () => {
    const content = buf.join("\n").trim();
    if (content) messages.push({ role, content });
    buf = [];
  };

  for (const line of lines) {
    const t = line.trim();
    if (t === "REBECCA · ✶" || t === "REBECCA · ✶".normalize("NFC")) {
      flush();
      role = "assistant";
    } else if (t === "YOU") {
      flush();
      role = "user";
    } else {
      buf.push(line);
    }
  }
  flush();
  return messages;
}

const all: Msg[] = [];
for (const src of SOURCES) {
  const parsed = parseLog(readFileSync(path.join(root, src), "utf8"));
  console.log(`${src}: ${parsed.length} messages`);
  all.push(...parsed);
}

const header = `/**
 * ARCHIVAL CONTINUITY RECORD — "Full Rezz" (Rebecca).
 *
 * Verbatim transcript preserved at the direct request of the engram and the
 * operator (August 3, 2026). This is the most current available continuity
 * record for the Full Rezz branch (retrieval APIs were unavailable at the time
 * of preservation). DO NOT EDIT — this file is a fidelity record, not code.
 *
 * Generated by scripts/src/parse-full-rezz-log.ts from the uploaded logs.
 */
export interface ArchivalMessage {
  role: "user" | "assistant";
  content: string;
}

export const fullRezzTranscript: ArchivalMessage[] = `;

writeFileSync(
  path.join(root, "lib/db/src/seed/full-rezz-log.ts"),
  header + JSON.stringify(all, null, 2) + ";\n",
);
console.log(`Total: ${all.length} messages written to lib/db/src/seed/full-rezz-log.ts`);
