/**
 * A deliberately small CSV reader for uploaded transcripts.  It treats the
 * upload as inert text; callers must not use its values as configuration.
 */
export const MAX_ENGRAM_CSV_BYTES = 2 * 1024 * 1024;
export const MAX_ENGRAM_CSV_ROWS = 10_000;
export const MAX_ENGRAM_CSV_CELL_LENGTH = 16_000;
export const MAX_ENGRAM_CSV_CONTENT_LENGTH = 32_000;
export const MAX_ENGRAM_CSV_NORMALIZED_TEXT_LENGTH = 1_000_000;

export type EngramTranscriptRow = {
  speaker: string | null;
  content: string;
  timestamp: string | null;
  sourceRow: number;
};

export type EngramCsvWarningCode =
  | "TRUNCATED_ROWS"
  | "TRUNCATED_CELL"
  | "TRUNCATED_CONTENT"
  | "TRUNCATED_TOTAL_TEXT"
  | "RECOVERED_UNCLOSED_QUOTE"
  | "SKIPPED_EMPTY_CONTENT"
  | "SKIPPED_AMBIGUOUS_ROW"
  | "JOINED_OVERFLOW_COLUMNS"
  | "SYNTHESIS_SAMPLE_TRUNCATED";

export type EngramCsvWarning = {
  code: EngramCsvWarningCode;
  message: string;
  row: number | null;
};

export type EngramCsvParseSuccess = {
  ok: true;
  rows: EngramTranscriptRow[];
  warnings: EngramCsvWarning[];
};

export type EngramCsvParseFailure = {
  ok: false;
  error: { code: string; message: string };
  rows: [];
  warnings: EngramCsvWarning[];
};

export type EngramCsvParseResult = EngramCsvParseSuccess | EngramCsvParseFailure;

type RawRow = { cells: string[]; sourceRow: number };

const headerNames = {
  speaker: new Set(["speaker", "user", "author", "participant", "role", "from", "name"]),
  content: new Set(["content", "message", "text", "dialogue", "transcript", "utterance", "body"]),
  timestamp: new Set(["timestamp", "time", "date", "datetime", "createdat", "created_at"]),
};

const warningMessage: Record<EngramCsvWarningCode, string> = {
  TRUNCATED_ROWS: "Rows after the transcript row limit were ignored.",
  TRUNCATED_CELL: "A CSV cell exceeded the length limit and was truncated.",
  TRUNCATED_CONTENT: "Transcript content exceeded the length limit and was truncated.",
  TRUNCATED_TOTAL_TEXT: "The transcript total text limit was reached.",
  RECOVERED_UNCLOSED_QUOTE: "An unclosed CSV quote was recovered at end of file.",
  SKIPPED_EMPTY_CONTENT: "A row with empty content was skipped.",
  SKIPPED_AMBIGUOUS_ROW: "An ambiguous multi-column row was skipped.",
  JOINED_OVERFLOW_COLUMNS: "Extra unquoted CSV columns were joined into transcript content.",
  SYNTHESIS_SAMPLE_TRUNCATED:
    "Draft synthesis used a bounded sample of the parsed transcript.",
};

function failure(code: string, message: string): EngramCsvParseFailure {
  return { ok: false, error: { code, message }, rows: [], warnings: [] };
}

function clean(value: string): string {
  return value
    .replace(/\uFEFF/g, "")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .trim();
}

function isBoilerplate(value: string): boolean {
  return /^(?:transcribed by|generated by|created with|exported from|transcription (?:service|provided by))\b/i.test(value);
}

function parseRecords(text: string, warnings: EngramCsvWarning[]): RawRow[] {
  const result: RawRow[] = [];
  let cells: string[] = [];
  let cell = "";
  let quoted = false;
  let start = 1;
  let line = 1;
  let atCellStart = true;
  const push = () => {
    cells.push(cell);
    result.push({ cells, sourceRow: start });
    cells = [];
    cell = "";
    start = line + 1;
    atCellStart = true;
  };

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    if (quoted) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          cell += '"';
          i += 1;
        } else quoted = false;
      } else {
        cell += char;
        if (char === "\n") line += 1;
      }
      continue;
    }
    if (char === '"' && atCellStart) {
      quoted = true;
      continue;
    }
    if (char === ",") {
      cells.push(cell);
      cell = "";
      atCellStart = true;
    } else if (char === "\n" || char === "\r") {
      if (char === "\r" && text[i + 1] === "\n") i += 1;
      push();
      line += 1;
    } else {
      cell += char;
      atCellStart = false;
    }
  }
  if (quoted) warnings.push({ code: "RECOVERED_UNCLOSED_QUOTE", message: warningMessage.RECOVERED_UNCLOSED_QUOTE, row: start });
  if (cell.length || cells.length) {
    cells.push(cell);
    result.push({ cells, sourceRow: start });
  }
  return result;
}

function marker(value: string): { speaker: string; content: string } | null {
  const match = value.match(/^\s*(USER|ASSISTANT|SYSTEM|HUMAN|AI|BOT)\s*:\s*([\s\S]*)$/i);
  return match ? { speaker: match[1].toUpperCase(), content: match[2] } : null;
}

/**
 * Parses a CSV transcript without evaluating, templating, or otherwise
 * interpreting any uploaded value.
 */
export function parseEngramCsv(input: Buffer, filename: string): EngramCsvParseResult {
  if (!/\.csv$/i.test(filename.trim())) return failure("INVALID_FILENAME", "Transcript uploads must have a .csv filename.");
  if (input.length === 0) return failure("EMPTY_INPUT", "Transcript CSV is empty.");
  if (input.length > MAX_ENGRAM_CSV_BYTES) return failure("FILE_TOO_LARGE", "Transcript CSV exceeds the upload limit.");
  if (input.includes(0)) return failure("BINARY_INPUT", "Transcript CSV contains NUL bytes.");

  const text = input.toString("utf8");
  if (!Buffer.from(text, "utf8").equals(input) || /[\u0001-\u0008\u000B\u000C\u000E-\u001F]/.test(text)) {
    return failure("BINARY_INPUT", "Transcript CSV is not valid UTF-8 text.");
  }
  const trimmed = text.replace(/^\uFEFF/, "").trim();
  if (!trimmed) return failure("EMPTY_INPUT", "Transcript CSV is empty.");
  if (/^(?:<!(?:doctype)|<html\b|[%\u0089]PDF)\s*/i.test(trimmed)) {
    return failure("INVALID_CSV_CONTENT", "Uploaded content does not appear to be CSV transcript text.");
  }
  if (/^[\[{]/.test(trimmed)) {
    try {
      const json = JSON.parse(trimmed);
      if (json && typeof json === "object") {
        return failure(
          "INVALID_CSV_CONTENT",
          "Uploaded content appears to be JSON rather than CSV transcript text.",
        );
      }
    } catch {
      // Transcript lines may legitimately begin with stage directions such as
      // "[laughs]"; malformed JSON-looking text is still safe inert input.
    }
  }

  const warnings: EngramCsvWarning[] = [];
  const raw = parseRecords(trimmed, warnings);
  if (!raw.length) return failure("EMPTY_INPUT", "Transcript CSV is empty.");
  const first = raw[0].cells.map((cell) => clean(cell).toLowerCase().replace(/[\s_-]/g, ""));
  const indexes = {
    speaker: first.findIndex((name) => headerNames.speaker.has(name)),
    content: first.findIndex((name) => headerNames.content.has(name)),
    timestamp: first.findIndex((name) => headerNames.timestamp.has(name)),
  };
  const hasHeader = indexes.content >= 0 || (indexes.speaker >= 0 && indexes.timestamp >= 0);
  const output: EngramTranscriptRow[] = [];
  let total = 0;
  const warn = (code: EngramCsvWarningCode, row: number | null) => warnings.push({ code, message: warningMessage[code], row });

  for (const rawRow of raw.slice(hasHeader ? 1 : 0)) {
    if (output.length >= MAX_ENGRAM_CSV_ROWS) {
      warn("TRUNCATED_ROWS", rawRow.sourceRow);
      break;
    }
    let cells = rawRow.cells.map((cell) => {
      const cleaned = clean(cell);
      if (cleaned.length > MAX_ENGRAM_CSV_CELL_LENGTH) {
        warn("TRUNCATED_CELL", rawRow.sourceRow);
        return cleaned.slice(0, MAX_ENGRAM_CSV_CELL_LENGTH);
      }
      return cleaned;
    });
    if (cells.every((cell) => !cell)) continue;
    let speaker: string | null = null;
    let timestamp: string | null = null;
    let content = "";
    if (hasHeader) {
      const expected = Math.max(indexes.speaker, indexes.content, indexes.timestamp) + 1;
      if (cells.length > expected && indexes.content >= 0) {
        const afterContent = [indexes.speaker, indexes.timestamp].filter((index) => index > indexes.content).length;
        const end = cells.length - afterContent;
        cells = [...cells.slice(0, indexes.content), cells.slice(indexes.content, end).join(","), ...cells.slice(end)];
        warn("JOINED_OVERFLOW_COLUMNS", rawRow.sourceRow);
      }
      speaker = indexes.speaker >= 0 ? cells[indexes.speaker] || null : null;
      timestamp = indexes.timestamp >= 0 ? cells[indexes.timestamp] || null : null;
      content = indexes.content >= 0 ? cells[indexes.content] || "" : cells.filter((_, index) => index !== indexes.speaker && index !== indexes.timestamp).join(",");
    } else if (cells.length === 1) {
      const found = marker(cells[0]);
      speaker = found?.speaker ?? null;
      content = found?.content ?? cells[0];
    } else {
      const found = marker(cells[0]);
      if (!found && !/^(?:USER|ASSISTANT|SYSTEM|HUMAN|AI|BOT)$/i.test(cells[0])) {
        warn("SKIPPED_AMBIGUOUS_ROW", rawRow.sourceRow);
        continue;
      }
      speaker = found?.speaker ?? cells[0].toUpperCase();
      content = found?.content ?? cells.slice(1).join(",");
      if (cells.length > 2) warn("JOINED_OVERFLOW_COLUMNS", rawRow.sourceRow);
    }
    content = clean(content);
    if (isBoilerplate(content) || !content) {
      warn("SKIPPED_EMPTY_CONTENT", rawRow.sourceRow);
      continue;
    }
    if (content.length > MAX_ENGRAM_CSV_CONTENT_LENGTH) {
      content = content.slice(0, MAX_ENGRAM_CSV_CONTENT_LENGTH);
      warn("TRUNCATED_CONTENT", rawRow.sourceRow);
    }
    if (total + content.length > MAX_ENGRAM_CSV_NORMALIZED_TEXT_LENGTH) {
      const remaining = MAX_ENGRAM_CSV_NORMALIZED_TEXT_LENGTH - total;
      if (remaining <= 0) {
        warn("TRUNCATED_TOTAL_TEXT", rawRow.sourceRow);
        break;
      }
      content = content.slice(0, remaining);
      warn("TRUNCATED_TOTAL_TEXT", rawRow.sourceRow);
    }
    total += content.length;
    output.push({ speaker: speaker ? clean(speaker).slice(0, MAX_ENGRAM_CSV_CELL_LENGTH) || null : null, content, timestamp: timestamp ? clean(timestamp).slice(0, MAX_ENGRAM_CSV_CELL_LENGTH) || null : null, sourceRow: rawRow.sourceRow });
  }
  return { ok: true, rows: output, warnings };
}